using CertDesk.Data; using System.Data;
namespace CertDesk.Forms;
public sealed class DashboardView:UserControl
{
 public DashboardView(){BackColor=Color.White; var root=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=3}; root.RowStyles.Add(new RowStyle(SizeType.AutoSize)); root.RowStyles.Add(new RowStyle(SizeType.Absolute,120)); root.RowStyles.Add(new RowStyle(SizeType.Percent,100)); root.Controls.Add(Ui.Label("Главная панель",18,true)); var cards=new FlowLayoutPanel{Dock=DockStyle.Fill}; foreach(var (t,v,c) in Metrics()) cards.Controls.Add(Card(t,v,c)); root.Controls.Add(cards); var grid=Ui.Grid(); grid.DataSource=Attention(); root.Controls.Add(grid); Controls.Add(root);} 
 Control Card(string title,string value,Color color){var p=new Panel{Width=180,Height=92,BackColor=Ui.Bg,Margin=new Padding(6),Padding=new Padding(12)}; var v=Ui.Label(value,22,true); v.ForeColor=color; var t=Ui.Label(title,9); t.ForeColor=Ui.Muted; t.Top=52; p.Controls.Add(v); p.Controls.Add(t); return p;}
 List<(string,string,Color)> Metrics(){using var c=Db.OpenConnection(); int Q(string sql){using var cmd=Db.Command(c,sql); return Convert.ToInt32(cmd.ExecuteScalar());} return [("действующие сертификаты",Q("SELECT COUNT(*) FROM certificates WHERE status='active'").ToString(),ColorTranslator.FromHtml("#2E7D32")),("сертификаты истекают",Q("SELECT COUNT(*) FROM certificates WHERE status='warning'").ToString(),ColorTranslator.FromHtml("#F39C12")),("действующие МЧД",Q("SELECT COUNT(*) FROM mchd WHERE status='active'").ToString(),ColorTranslator.FromHtml("#2E7D32")),("МЧД истекают",Q("SELECT COUNT(*) FROM mchd WHERE status='warning'").ToString(),ColorTranslator.FromHtml("#F39C12")),("всего токенов",Q("SELECT COUNT(*) FROM tokens").ToString(),Ui.Blue),("выданные токены",Q("SELECT COUNT(*) FROM tokens WHERE status='issued'").ToString(),Ui.Blue),("активные сотрудники",Q("SELECT COUNT(*) FROM employees WHERE is_active=1").ToString(),Ui.Blue)];}
 DataTable Attention(){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,@"SELECT 'Сертификат' AS 'Тип записи', c.serial_number AS 'Номер', e.full_name AS 'Владелец/представитель', c.valid_to AS 'Действует до', CAST(julianday(c.valid_to)-julianday('now','start of day') AS INT) AS 'Осталось дней', c.status AS 'Статус' FROM certificates c JOIN employees e ON e.id=c.employee_id WHERE c.status IN ('warning','expired') UNION ALL SELECT 'МЧД', m.number, e.full_name, m.valid_to, CAST(julianday(m.valid_to)-julianday('now','start of day') AS INT), m.status FROM mchd m JOIN employees e ON e.id=m.representative_employee_id WHERE m.status IN ('warning','expired') ORDER BY 'Действует до'"); var dt=new DataTable(); dt.Load(cmd.ExecuteReader()); return dt;}
}
