using CertDesk.Data; using CertDesk.Models; using System.Data;
namespace CertDesk.Services;
public sealed class CertificateService(User user)
{
 public DataTable Search(string q,string status,string type){RefreshStatuses(); using var c=Db.OpenConnection(); var sw=status=="Все"?"":" AND c.status=@st"; var tw=type=="Все"?"":" AND c.signature_type=@tp"; using var cmd=Db.Command(c,$"SELECT c.id,c.serial_number AS 'Серийный номер',e.full_name AS 'Владелец',c.signature_type AS 'Тип подписи',a.name AS 'Удостоверяющий центр',COALESCE(t.inventory_number,'') AS 'Токен',date(c.issued_at) AS 'Дата выдачи',date(c.valid_to) AS 'Действует до',CAST(julianday(c.valid_to)-julianday('now','start of day') AS INT) AS 'Осталось дней',CASE c.status WHEN 'active' THEN 'действует' WHEN 'warning' THEN 'истекает' WHEN 'expired' THEN 'истек' WHEN 'revoked' THEN 'отозван' ELSE 'архивный' END AS 'Статус' FROM certificates c JOIN employees e ON e.id=c.employee_id JOIN authorities a ON a.id=c.authority_id LEFT JOIN tokens t ON t.id=c.token_id WHERE (c.serial_number LIKE @q OR e.full_name LIKE @q OR a.name LIKE @q){sw}{tw} ORDER BY c.valid_to",("@q",$"%{q}%"),("@st",status),("@tp",type)); var dt=new DataTable(); dt.Load(cmd.ExecuteReader()); return dt;}
 public Certificate? Get(int id){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"SELECT id,employee_id,authority_id,token_id,serial_number,signature_type,issued_at,valid_from,valid_to,status,purpose,is_archived FROM certificates WHERE id=@id",("@id",id)); using var r=cmd.ExecuteReader(); return r.Read()?new Certificate{Id=r.GetInt32(0),EmployeeId=r.GetInt32(1),AuthorityId=r.GetInt32(2),TokenId=r.IsDBNull(3)?null:r.GetInt32(3),SerialNumber=r.GetString(4),SignatureType=r.GetString(5),IssuedAt=DateTime.Parse(r.GetString(6)),ValidFrom=DateTime.Parse(r.GetString(7)),ValidTo=DateTime.Parse(r.GetString(8)),Status=r.GetString(9),Purpose=r[10] as string,IsArchived=r.GetInt32(11)==1}:null;}
 public void Save(Certificate e){Validate(e); e.Status=StatusService.Calculate(e.ValidTo,e.Status); using var c=Db.OpenConnection(); var isNew=e.Id==0; using var cmd=isNew?Db.Command(c,"INSERT INTO certificates(employee_id,authority_id,token_id,serial_number,signature_type,issued_at,valid_from,valid_to,status,purpose,is_archived) VALUES(@e,@a,@t,@s,@sg,@ia,@vf,@vt,@st,@p,0)",P(e)):Db.Command(c,"UPDATE certificates SET employee_id=@e,authority_id=@a,token_id=@t,serial_number=@s,signature_type=@sg,issued_at=@ia,valid_from=@vf,valid_to=@vt,status=@st,purpose=@p WHERE id=@id",P(e).Append(("@id",e.Id)).ToArray()); try{cmd.ExecuteNonQuery();}catch(Exception ex){throw new InvalidOperationException("Серийный номер сертификата должен быть уникальным",ex);} new AuditService(user).Log(isNew?"создание сертификата":"изменение сертификата","certificate",isNew?(int)c.LastInsertRowId:e.Id,e.SerialNumber);}
 public void SetStatus(int id,string status,string action){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"UPDATE certificates SET status=@s,is_archived=CASE WHEN @s='archived' THEN 1 ELSE is_archived END WHERE id=@id",("@s",status),("@id",id)); cmd.ExecuteNonQuery(); new AuditService(user).Log(action,"certificate",id);}
 public void RefreshStatuses(){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"UPDATE certificates SET status=CASE WHEN date(valid_to)<date('now') THEN 'expired' WHEN julianday(valid_to)-julianday('now','start of day')<=30 THEN 'warning' ELSE 'active' END WHERE status NOT IN ('revoked','archived')"); cmd.ExecuteNonQuery();}
 private static (string,object?)[] P(Certificate e)=>[("@e",e.EmployeeId),("@a",e.AuthorityId),("@t",e.TokenId),("@s",e.SerialNumber),("@sg",e.SignatureType),("@ia",e.IssuedAt.ToString("yyyy-MM-dd")),("@vf",e.ValidFrom.ToString("yyyy-MM-dd")),("@vt",e.ValidTo.ToString("yyyy-MM-dd")),("@st",e.Status),("@p",e.Purpose)];
 private static void Validate(Certificate e){if(e.EmployeeId==0||e.AuthorityId==0||string.IsNullOrWhiteSpace(e.SerialNumber)) throw new InvalidOperationException("Владелец, УЦ и серийный номер обязательны"); if(e.ValidTo<e.ValidFrom||e.IssuedAt>e.ValidTo) throw new InvalidOperationException("Проверьте корректность дат");}
}
