using CertDesk.Data; using CertDesk.Models; using System.Data;
namespace CertDesk.Services;
public sealed class EmployeeService(User user)
{
 public DataTable Search(string q,string state){using var c=Db.OpenConnection(); var where=state=="Активные"?" AND is_active=1":state=="Архивные"?" AND is_active=0":""; using var cmd=Db.Command(c,$"SELECT id,full_name AS 'ФИО',position AS 'Должность',COALESCE(department,'') AS 'Подразделение',COALESCE(email,'') AS 'Email',COALESCE(phone,'') AS 'Телефон',CASE is_active WHEN 1 THEN 'активен' ELSE 'архивный' END AS 'Статус' FROM employees WHERE (full_name LIKE @q OR position LIKE @q OR COALESCE(department,'') LIKE @q OR COALESCE(email,'') LIKE @q){where} ORDER BY full_name",("@q",$"%{q}%")); var dt=new DataTable(); dt.Load(cmd.ExecuteReader()); return dt;}
 public Employee? Get(int id){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"SELECT id,full_name,position,department,email,phone,snils,inn,is_active FROM employees WHERE id=@id",("@id",id)); using var r=cmd.ExecuteReader(); return r.Read()?new Employee{Id=r.GetInt32(0),FullName=r.GetString(1),Position=r.GetString(2),Department=r[3] as string,Email=r[4] as string,Phone=r[5] as string,Snils=r[6] as string,Inn=r[7] as string,IsActive=r.GetInt32(8)==1}:null;}
 public void Save(Employee e){Validate(e); using var c=Db.OpenConnection(); var isNew=e.Id==0; using var cmd=isNew?Db.Command(c,"INSERT INTO employees(full_name,position,department,email,phone,snils,inn,is_active) VALUES(@n,@p,@d,@e,@ph,@s,@i,@a)",P(e)):Db.Command(c,"UPDATE employees SET full_name=@n,position=@p,department=@d,email=@e,phone=@ph,snils=@s,inn=@i,is_active=@a WHERE id=@id",P(e).Append(("@id",e.Id)).ToArray()); cmd.ExecuteNonQuery(); new AuditService(user).Log(isNew?"создание сотрудника":"изменение сотрудника","employee",isNew?(int)c.LastInsertRowId:e.Id,e.FullName);}
 public void Archive(int id){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"UPDATE employees SET is_active=0 WHERE id=@id",("@id",id)); cmd.ExecuteNonQuery(); new AuditService(user).Log("архивирование сотрудника","employee",id);}
 private static (string,object?)[] P(Employee e)=>[("@n",e.FullName),("@p",e.Position),("@d",e.Department),("@e",e.Email),("@ph",e.Phone),("@s",e.Snils),("@i",e.Inn),("@a",e.IsActive?1:0)];
 private static void Validate(Employee e){if(string.IsNullOrWhiteSpace(e.FullName)||string.IsNullOrWhiteSpace(e.Position)) throw new InvalidOperationException("ФИО и должность обязательны"); if(!string.IsNullOrWhiteSpace(e.Email)&&!e.Email.Contains('@')) throw new InvalidOperationException("Некорректный email");}
}
