using CertDesk.Data; using CertDesk.Models; using System.Data;
namespace CertDesk.Services;
public sealed class MchdService(User user)
{
 public DataTable Search(string q,string status,string reg){RefreshStatuses(); using var c=Db.OpenConnection(); var sw=status=="Все"?"":" AND m.status=@st"; var rw=reg=="Все"?"":reg=="Зарегистрирована"?" AND m.is_registered=1":" AND m.is_registered=0"; using var cmd=Db.Command(c,$"SELECT m.id,m.number AS 'Номер МЧД',COALESCE(p.full_name,'') AS 'Доверитель',r.full_name AS 'Представитель',COALESCE(c.serial_number,'') AS 'Сертификат',m.powers AS 'Полномочия',date(m.valid_from) AS 'Действует с',date(m.valid_to) AS 'Действует до',CAST(julianday(m.valid_to)-julianday('now','start of day') AS INT) AS 'Осталось дней',CASE m.is_registered WHEN 1 THEN 'да' ELSE 'нет' END AS 'Регистрация',CASE m.status WHEN 'active' THEN 'действует' WHEN 'warning' THEN 'истекает' WHEN 'expired' THEN 'истек' WHEN 'revoked' THEN 'отозвана' ELSE 'архивная' END AS 'Статус' FROM mchd m LEFT JOIN employees p ON p.id=m.principal_employee_id JOIN employees r ON r.id=m.representative_employee_id LEFT JOIN certificates c ON c.id=m.certificate_id WHERE (m.number LIKE @q OR r.full_name LIKE @q OR m.powers LIKE @q){sw}{rw} ORDER BY m.valid_to",("@q",$"%{q}%"),("@st",status)); var dt=new DataTable(); dt.Load(cmd.ExecuteReader()); return dt;}
 public Mchd? Get(int id){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"SELECT id,number,principal_employee_id,representative_employee_id,certificate_id,powers,powers_codes,valid_from,valid_to,is_registered,status,notes FROM mchd WHERE id=@id",("@id",id)); using var r=cmd.ExecuteReader(); return r.Read()?new Mchd{Id=r.GetInt32(0),Number=r.GetString(1),PrincipalEmployeeId=r.IsDBNull(2)?null:r.GetInt32(2),RepresentativeEmployeeId=r.GetInt32(3),CertificateId=r.IsDBNull(4)?null:r.GetInt32(4),Powers=r.GetString(5),PowersCodes=r[6] as string,ValidFrom=DateTime.Parse(r.GetString(7)),ValidTo=DateTime.Parse(r.GetString(8)),IsRegistered=r.GetInt32(9)==1,Status=r.GetString(10),Notes=r[11] as string}:null;}
 public void Save(Mchd e){Validate(e); e.Status=StatusService.Calculate(e.ValidTo,e.Status); using var c=Db.OpenConnection(); var isNew=e.Id==0; using var cmd=isNew?Db.Command(c,"INSERT INTO mchd(number,principal_employee_id,representative_employee_id,certificate_id,powers,powers_codes,valid_from,valid_to,is_registered,status,notes) VALUES(@n,@p,@r,@c,@pw,@pc,@vf,@vt,@reg,@st,@no)",P(e)):Db.Command(c,"UPDATE mchd SET number=@n,principal_employee_id=@p,representative_employee_id=@r,certificate_id=@c,powers=@pw,powers_codes=@pc,valid_from=@vf,valid_to=@vt,is_registered=@reg,status=@st,notes=@no WHERE id=@id",P(e).Append(("@id",e.Id)).ToArray()); try{cmd.ExecuteNonQuery();}catch(Exception ex){throw new InvalidOperationException("Номер МЧД должен быть уникальным",ex);} new AuditService(user).Log(isNew?"создание МЧД":"изменение МЧД","mchd",isNew?(int)c.LastInsertRowId:e.Id,e.Number);}
 public void SetStatus(int id,string status,string action){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"UPDATE mchd SET status=@s WHERE id=@id",("@s",status),("@id",id)); cmd.ExecuteNonQuery(); new AuditService(user).Log(action,"mchd",id);}
 public void RefreshStatuses(){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"UPDATE mchd SET status=CASE WHEN date(valid_to)<date('now') THEN 'expired' WHEN julianday(valid_to)-julianday('now','start of day')<=30 THEN 'warning' ELSE 'active' END WHERE status NOT IN ('revoked','archived')"); cmd.ExecuteNonQuery();}
 private static (string,object?)[] P(Mchd e)=>[("@n",e.Number),("@p",e.PrincipalEmployeeId),("@r",e.RepresentativeEmployeeId),("@c",e.CertificateId),("@pw",e.Powers),("@pc",e.PowersCodes),("@vf",e.ValidFrom.ToString("yyyy-MM-dd")),("@vt",e.ValidTo.ToString("yyyy-MM-dd")),("@reg",e.IsRegistered?1:0),("@st",e.Status),("@no",e.Notes)];
 private static void Validate(Mchd e){if(string.IsNullOrWhiteSpace(e.Number)||e.RepresentativeEmployeeId==0||string.IsNullOrWhiteSpace(e.Powers)) throw new InvalidOperationException("Номер, представитель и полномочия обязательны"); if(e.ValidTo<e.ValidFrom) throw new InvalidOperationException("Дата окончания не может быть раньше даты начала");}
}
