using CertDesk.Data; using CertDesk.Models; using System.Data;
namespace CertDesk.Services;
public sealed class TokenService(CurrentUser user)
{
 public DataTable Search(string q,string status){using var c=Db.OpenConnection(); var sw=status=="Все"?"":" AND t.status=@st"; using var cmd=Db.Command(c,$"SELECT t.id,t.inventory_number AS 'Инвентарный номер',t.token_type AS 'Тип',COALESCE(t.model,'') AS 'Модель',COALESCE(t.serial_number,'') AS 'Серийный номер',CASE t.status WHEN 'storage' THEN 'на хранении' WHEN 'issued' THEN 'выдан' WHEN 'damaged' THEN 'поврежден' ELSE 'списан' END AS 'Статус',COALESCE(e.full_name,'') AS 'Текущий держатель',COALESCE(date(t.received_at),'') AS 'Дата поступления',COALESCE(t.notes,'') AS 'Примечание' FROM tokens t LEFT JOIN employees e ON e.id=t.holder_id WHERE (t.inventory_number LIKE @q OR COALESCE(t.model,'') LIKE @q OR COALESCE(t.serial_number,'') LIKE @q OR COALESCE(e.full_name,'') LIKE @q){sw} ORDER BY t.inventory_number",("@q",$"%{q}%"),("@st",status)); var dt=new DataTable(); dt.Load(cmd.ExecuteReader()); return dt;}
 public Token? Get(int id){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"SELECT id,inventory_number,token_type,model,serial_number,status,holder_id,received_at,notes FROM tokens WHERE id=@id",("@id",id)); using var r=cmd.ExecuteReader(); return r.Read()?new Token{Id=r.GetInt32(0),InventoryNumber=r.GetString(1),TokenType=r.GetString(2),Model=r[3] as string,SerialNumber=r[4] as string,Status=r.GetString(5),HolderId=r.IsDBNull(6)?null:r.GetInt32(6),ReceivedAt=r.IsDBNull(7)?null:DateTime.Parse(r.GetString(7)),Notes=r[8] as string}:null;}
 public void Save(Token e){Validate(e); using var c=Db.OpenConnection(); var isNew=e.Id==0; using var cmd=isNew?Db.Command(c,"INSERT INTO tokens(inventory_number,token_type,model,serial_number,status,holder_id,received_at,notes) VALUES(@i,@t,@m,@s,@st,@h,@r,@n)",P(e)):Db.Command(c,"UPDATE tokens SET inventory_number=@i,token_type=@t,model=@m,serial_number=@s,status=@st,holder_id=@h,received_at=@r,notes=@n WHERE id=@id",P(e).Append(("@id",e.Id)).ToArray()); try{cmd.ExecuteNonQuery();}catch(Exception ex){throw new InvalidOperationException("Инвентарный или серийный номер токена должен быть уникальным",ex);} new AuditService(user).Log(isNew?"создание токена":"изменение токена","token",isNew?(int)c.LastInsertRowId:e.Id,e.InventoryNumber);}
 public void Issue(int tokenId,int employeeId,string act,string comment){Operate(tokenId,employeeId,"issued","issue",act,comment,"выдача токена");}
 public void Return(int tokenId,string comment)=>Operate(tokenId,null,"storage","return",null,comment,"возврат токена");
 public void Damage(int tokenId,string comment)=>Operate(tokenId,null,"damaged","damage",null,comment,"повреждение токена");
 public void WriteOff(int tokenId,string comment)=>Operate(tokenId,null,"written_off","write_off",null,comment,"списание токена");
 private void Operate(int tokenId,int? employeeId,string status,string op,string? act,string? comment,string audit){using var c=Db.OpenConnection(); using var tx=c.BeginTransaction(); try{using(var cmd=Db.Command(c,tx,"UPDATE tokens SET status=@s,holder_id=@h WHERE id=@id",("@s",status),("@h",status=="issued"?employeeId:null),("@id",tokenId)))cmd.ExecuteNonQuery(); using(var cmd=Db.Command(c,tx,"INSERT INTO token_operations(token_id,employee_id,operation,act_number,comment,operator_user_id) VALUES(@t,@e,@o,@a,@c,@u)",("@t",tokenId),("@e",employeeId),("@o",op),("@a",act),("@c",comment),("@u",user.Id)))cmd.ExecuteNonQuery(); using(var cmd=Db.Command(c,tx,"INSERT INTO audit_log(user_id,login,action,entity_type,entity_id,description) VALUES(@u,@l,@a,'token',@id,@d)",("@u",user.Id),("@l",user.Login),("@a",audit),("@id",tokenId),("@d",comment)))cmd.ExecuteNonQuery(); tx.Commit();}catch{tx.Rollback();throw;}}
 private static (string,object?)[] P(Token e)=>[("@i",e.InventoryNumber),("@t",e.TokenType),("@m",e.Model),("@s",e.SerialNumber),("@st",e.Status),("@h",e.HolderId),("@r",e.ReceivedAt?.ToString("yyyy-MM-dd")),("@n",e.Notes)];
 private static void Validate(Token e){if(string.IsNullOrWhiteSpace(e.InventoryNumber)||string.IsNullOrWhiteSpace(e.TokenType)) throw new InvalidOperationException("Инвентарный номер и тип токена обязательны");}
 public DataTable Related(int tokenId){using var c=Db.OpenConnection(); using var cmd=Db.Command(c,"SELECT serial_number AS 'Сертификат', valid_to AS 'Действует до', status AS 'Статус' FROM certificates WHERE token_id=@id; SELECT 1",("@id",tokenId)); var dt=new DataTable(); dt.Load(cmd.ExecuteReader()); return dt;}
}
